### ISSUE TITLE
插件发出指令时报错

### ISSUE THREAD

**Issue by yujing191025** [Nwflower/auto-plugin#11]
SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at Response.json (file:///root/Yunzai-Bot/node_modules/.pnpm/node-fetch@3.3.1/node_modules/node-fetch/src/body.js:148:15)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async answer (file:///root/Yunzai-Bot/plugins/hs-qiqi-plugin/apps/ai.js:406:9)
自动化插件所有指令都会报这个

**Comment by yujing191025** [comment]
麻烦大佬帮忙看一下
